// <auto-generated />
namespace ABC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class domingo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(domingo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191245534_domingo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
